name: Linter CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
      #   matrix:
      node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint
